-- MySQL Script generated by MySQL Workbench
-- Data criação: 28/04/2025
-- Model: dbViveiro    Version: 1.0


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbviveiro
-- -----------------------------------------------------

-- CRIAÇÃO DE TABELAS
-- Tabela `categoria_planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria_planta` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Tabela `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Tabela `especie_planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `especie_planta` (
  `id_especie` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_especie`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Tabela `especie_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `especie_categoria` (
  `id_especie` INT(11) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  PRIMARY KEY (`id_especie`, `id_categoria`),
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `especie_categoria_ibfk_1`
    FOREIGN KEY (`id_especie`)
    REFERENCES `especie_planta` (`id_especie`),
  CONSTRAINT `especie_categoria_ibfk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `categoria_planta` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Tabela `estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque` (
  `id_estoque` INT(11) NOT NULL AUTO_INCREMENT,
  `id_especie` INT(11) NULL DEFAULT NULL,
  `quantidade` INT(11) NOT NULL,
  PRIMARY KEY (`id_estoque`),
  INDEX `id_especie` (`id_especie` ASC) VISIBLE,
  CONSTRAINT `estoque_ibfk_1`
    FOREIGN KEY (`id_especie`)
    REFERENCES `especie_planta` (`id_especie`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Tabela `muda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `muda` (
  `id_muda` INT(11) NOT NULL AUTO_INCREMENT,
  `id_especie` INT(11) NULL DEFAULT NULL,
  `data_producao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_muda`),
  INDEX `id_especie` (`id_especie` ASC) VISIBLE,
  CONSTRAINT `muda_ibfk_1`
    FOREIGN KEY (`id_especie`)
    REFERENCES `especie_planta` (`id_especie`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Tabela `venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda` (
  `id_venda` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(11) NULL DEFAULT NULL,
  `data_venda` DATE NULL DEFAULT NULL,
  `valor_total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `venda_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `cliente` (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Tabela `venda_muda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_muda` (
  `id_venda` INT(11) NOT NULL,
  `id_muda` INT(11) NOT NULL,
  PRIMARY KEY (`id_venda`, `id_muda`),
  INDEX `id_muda` (`id_muda` ASC) VISIBLE,
  CONSTRAINT `venda_muda_ibfk_1`
    FOREIGN KEY (`id_venda`)
    REFERENCES `venda` (`id_venda`),
  CONSTRAINT `venda_muda_ibfk_2`
    FOREIGN KEY (`id_muda`)
    REFERENCES `muda` (`id_muda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Populando tabelas
-- -----------------------------------------------------
		-- * Tabela `especie_planta`
INSERT INTO Especie_Planta (nome, preco_unitario) VALUES
('Rosa', 46.88), ('Limoeiro', 83.99), ('Lavanda', 78.94), ('Jasmim', 17.19), ('Manjericão', 25.61),
('Alecrim', 68.55), ('Orquídea', 21.74), ('Hibisco', 52.79), ('Suculenta', 93.38), ('Begônia', 96.79),
('Antúrio', 23.27), ('Espada-de-São-Jorge', 43.22), ('Ficus', 19.79), ('Bromélia', 40.34), ('Cactos', 62.68),
('Samambaia', 83.48), ('Costela-de-Adão', 31.73), ('Zamioculca', 99.16), ('Azaleia', 94.83), ('Camélia', 63.89),
('Dália', 78.92), ('Ciclanto', 53.13), ('Cróton', 68.31), ('Gardênia', 63.62), ('Ipê-amarelo', 78.02),
('Pata-de-vaca', 26.38), ('Palmeira-areca', 40.83), ('Pitanga', 18.36), ('Jabuticabeira', 72.82), ('Amor-perfeito', 40.88);

		-- * Tabela `categoria_planta`
INSERT INTO Categoria_Planta (nome) VALUES
('Ornamental'), ('Frutífera'), ('Medicinal'), ('Aromática'), ('Trepadeira'), ('Florífera'), ('Suculenta'),
('Cercas vivas'), ('Planta de sombra'), ('Planta de sol'), ('Folhagem decorativa'), ('Palmeira'),
('Árvore nativa'), ('Árvore exótica'), ('Herbácea'), ('Tóxica'), ('Aquática'), ('Planta pendente'),
('Atrativa para polinizadores'), ('Resistente à seca'), ('Atrativa para pássaros'), ('Bonsai'),
('Planta rasteira'), ('Planta trepadeira'), ('Perene'), ('Anual'), ('De clima frio'), ('De clima tropical'),
('De fácil cultivo'), ('Planta para vasos');

		-- * Tabela `especie_categoria`
INSERT INTO Especie_Categoria (id_especie, id_categoria) VALUES
(1,1), (2,2), (3,3), (4,4), (5,5), (6,6), (7,7), (8,8), (9,9), (10,10),
(11,11), (12,12), (13,13), (14,14), (15,15), (16,16), (17,17), (18,18), (19,19), (20,20),
(21,21), (22,22), (23,23), (24,24), (25,25), (26,26), (27,27), (28,28), (29,29), (30,30);

		-- * Tabela `estoque`
INSERT INTO Estoque (id_especie, quantidade) VALUES
(1,41), (2,93), (3,15), (4,24), (5,39), (6,53), (7,24), (8,14), (9,65), (10,55),
(11,34), (12,74), (13,11), (14,35), (15,34), (16,63), (17,56), (18,73), (19,34), (20,64),
(21,48), (22,82), (23,22), (24,64), (25,67), (26,19), (27,99), (28,19), (29,89), (30,90);

		-- * Tabela `muda`
INSERT INTO Muda (id_especie, data_producao) VALUES
(25, '2024-03-01'), (9, '2024-01-23'), (4, '2024-05-17'), (13, '2024-06-11'), (9, '2024-06-25'),
(3, '2024-03-27'), (30, '2024-06-15'), (6, '2024-09-26'), (15, '2024-07-05'), (2, '2024-01-28'),
(21, '2024-10-30'), (14, '2024-06-13'), (27, '2024-05-25'), (17, '2024-02-03'), (10, '2024-01-14'),
(6, '2024-06-28'), (29, '2024-07-20'), (20, '2024-01-24'), (16, '2024-02-10'), (5, '2024-09-22'),
(13, '2024-04-09'), (14, '2024-11-01'), (18, '2024-03-01'), (17, '2024-05-09'), (27, '2024-06-15'),
(20, '2024-08-24'), (5, '2024-01-16'), (24, '2024-07-22'), (4, '2024-09-13'), (6, '2024-04-16');

		-- * Tabela `cliente`
INSERT INTO Cliente (nome, telefone) VALUES
('João da Silva', '11934123983'), ('Maria Oliveira', '11902958203'), ('Carlos Souza', '11982747892'),
('Ana Beatriz', '11920856384'), ('Marcos Paulo', '11927465192'), ('Fernanda Lima', '11926501577'),
('Bruno Rocha', '11956382900'), ('Luciana Dias', '11953693993'), ('Paulo Henrique', '11995040564'),
('Juliana Mendes', '11977398662'), ('Rodrigo Alves', '11987941461'), ('Camila Reis', '11936854182'),
('Gabriel Costa', '11997008762'), ('Larissa Martins', '11983270977'), ('Tiago Barbosa', '11995347694'),
('Patrícia Gomes', '11998610037'), ('Eduardo Mello', '11987422657'), ('Isabela Nunes', '11962409426'),
('Renato Silva', '11968843827'), ('Sabrina Ferreira', '11968539093'), ('André Monteiro', '11959085598'),
('Carla Araújo', '11942879299'), ('Diego Ramos', '11992726902'), ('Natália Cardoso', '11951917646'),
('Vinícius Teixeira', '11910144491'), ('Aline Farias', '11931344185'), ('Fábio Campos', '11993993683'),
('Tânia Brito', '11922429353'), ('Ricardo Pinto', '11971018826'), ('Viviane Soares', '11930609049');

		-- * Tabela `venda`
INSERT INTO venda (id_venda, id_cliente, data_venda, valor_total)
VALUES 
    (1, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 350.75),
    (2, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 120.50),
    (3, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 215.99),
    (4, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 645.25),
    (5, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 452.10),
    (6, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 890.60),
    (7, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 1000.99),
    (8, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 765.43),
    (9, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 310.80),
    (10, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 129.40),
    (11, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 500.15),
    (12, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 212.55),
    (13, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 378.00),
    (14, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 655.99),
    (15, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 420.35),
    (16, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 199.99),
    (17, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 302.10),
    (18, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 849.50),
    (19, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 156.45),
    (20, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 230.99),
    (21, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 410.60),
    (22, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 977.00),
    (23, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 685.40),
    (24, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 315.75),
    (25, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 455.25),
    (26, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 150.00),
    (27, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 780.60),
    (28, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 243.10),
    (29, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 391.75),
    (30, FLOOR(1 + RAND() * 50), DATE_ADD('2025-04-01', INTERVAL FLOOR(RAND() * 14) DAY), 1120.80);

		-- * Tabela `venda_muda`
        INSERT INTO venda_muda (id_venda, id_muda)
VALUES 
    (1, FLOOR(1 + (RAND() * 30))),
    (2, FLOOR(1 + (RAND() * 30))),
    (3, FLOOR(1 + (RAND() * 30))),
    (4, FLOOR(1 + (RAND() * 30))),
    (5, FLOOR(1 + (RAND() * 30))),
    (6, FLOOR(1 + (RAND() * 30))),
    (7, FLOOR(1 + (RAND() * 30))),
    (8, FLOOR(1 + (RAND() * 30))),
    (9, FLOOR(1 + (RAND() * 30))),
    (10, FLOOR(1 + (RAND() * 30))),
    (11, FLOOR(1 + (RAND() * 30))),
    (12, FLOOR(1 + (RAND() * 30))),
    (13, FLOOR(1 + (RAND() * 30))),
    (14, FLOOR(1 + (RAND() * 30))),
    (15, FLOOR(1 + (RAND() * 30))),
    (16, FLOOR(1 + (RAND() * 30))),
    (17, FLOOR(1 + (RAND() * 30))),
    (18, FLOOR(1 + (RAND() * 30))),
    (19, FLOOR(1 + (RAND() * 30))),
    (20, FLOOR(1 + (RAND() * 30))),
    (21, FLOOR(1 + (RAND() * 30))),
    (22, FLOOR(1 + (RAND() * 30))),
    (23, FLOOR(1 + (RAND() * 30))),
    (24, FLOOR(1 + (RAND() * 30))),
    (25, FLOOR(1 + (RAND() * 30))),
    (26, FLOOR(1 + (RAND() * 30))),
    (27, FLOOR(1 + (RAND() * 30))),
    (28, FLOOR(1 + (RAND() * 30))),
    (29, FLOOR(1 + (RAND() * 30))),
    (30, FLOOR(1 + (RAND() * 30)));
    
    






